version: "3"

services:
  postgres:
    restart: always
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - "./db/.env"

  api:
    build: ./api
    # restart: always
    restart: always 
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    volumes:
      - ./api/:/api/
    env_file:
      - ./api/.env
    command: >
      sh -c "sleep 2 && uvicorn main:app --reload --host 0.0.0.0"
